spring.application.name=todo

#以下を追加
# H2 Console を有効化
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:tododb
# snake_case の列名 → camelCase のフィールドに自動マッピング
mybatis.configuration.map-underscore-to-camel-case=true
